In [157]:
import numpy as np

problemFile = "mlpy/geneticAlgorithm/bin1data/N1C1W1_A.BPP"

In [158]:
problemSet = []

with open(problemFile, "r") as file:
    for line in file:
        problemSet.append(int(line.strip('\n')))

In [159]:
numberOfItems = problemSet.pop(0)
binCapacity = problemSet.pop(0)

numberOfItems, binCapacity

(50, 100)

In [160]:
problemSet = np.array(problemSet)

assert numberOfItems == problemSet.size

problemSet

array([99, 99, 96, 96, 92, 92, 91, 88, 87, 86, 85, 76, 74, 72, 69, 67, 67,
       62, 61, 56, 52, 51, 49, 46, 44, 42, 40, 40, 33, 33, 30, 30, 29, 28,
       28, 27, 25, 24, 23, 22, 21, 20, 17, 14, 13, 11, 10,  7,  7,  3])

In [167]:
chromosome = np.arange(problemSet.size)
np.random.shuffle(chromosome)

chromosome

array([24, 14, 23, 25,  9,  4, 22, 36, 34, 27, 10, 33, 35, 43,  2,  3, 20,
       31, 26, 18, 37, 19, 13, 11,  1, 38, 39, 32, 46,  5, 12, 16, 41, 42,
       28, 30, 48, 44, 29, 47,  6,  8, 45,  0, 40,  7, 49, 21, 15, 17])

In [168]:
mappedChromosome = np.zeros(numberOfItems, dtype=int)
np.add.at(mappedChromosome, chromosome, problemSet)

mappedChromosome

array([14, 44, 69, 67, 92, 33, 21, 11, 20, 92, 85, 46, 30, 49, 99,  7, 30,
        3, 56, 51, 67,  7, 91, 96, 99, 96, 61, 86, 28, 23, 27, 62, 40, 76,
       87, 74, 88, 52, 42, 40, 13, 29, 28, 72, 24, 17, 33, 22, 25, 10])

In [169]:
# TODO: This is not complete
result = np.cumsum(mappedChromosome)
binsRequired = 0
while True:
    if np.max(result) > binCapacity:
        result = result - binCapacity
    else:
        binsRequired += 1
        break
    binsRequired += 1
    

binsRequired

25